#!/bin/sh
if grep Red /etc/issue > /dev/null 2>&1
then
	echo -n rh
	grep Red /etc/issue |cut -f5 -d' '
elif grep Fedora /etc/issue > /dev/null 2>&1
then
	echo -n fc
	grep Fedora /etc/issue |cut -f4 -d' '
elif grep CentOS /etc/issue > /dev/null 2>&1
then
	echo -n el
	grep CentOS /etc/issue |cut -f3 -d' ' |cut -f1 -d.
else
	echo UNKNOWN
fi
